#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

if [[ `which flake8` ]]; then
    PEPTOOL="flake8"
elif [[ `which pep8` ]]; then
    PEPTOOL="pep8"
else
    echo "You have to have either pep8 or flake8 installed"
    exit 1
fi

echo "Using $PEPTOOL to check your code." 
DIFFS="$(git diff --staged -z $against -U0 | pep8 --diff --max-line-length 80)"

if [[ $DIFFS ]]; then
    cat <<\EOF
______ ___________      _____ 
| ___ \  ___| ___ \    |  _  |
| |_/ / |__ | |_/ /_____\ V / 
|  __/|  __||  __/______/ _ \ 
| |   | |___| |        | |_| |
\_|   \____/\_|        \_____/
-----------------------------------------------------------------------
| Violations found in your changes, please fix them before committing |
-----------------------------------------------------------------------

EOF
    echo "$DIFFS" | sed "s/^\.\///"
    exit 1
fi
